---
# tasks file for gateway
- name: ensure that there is an internet gateway
  ec2_vpc_igw: 
    region: "{{ ec2_region  }}"
    vpc_id: "{{ vpc_info.vpc.id }}"
    tags:
      "Name": "{{ environment_name}}_internet_gateway"
      "Environment": "{{ environment_name }}"
      "Use": "gateway"
  register: igw_info

- name: print the onformation we have registered
  debug:
    msg: "{{ igw_info }}"

- name: check that we can route trough internet gateway
  ec2_vpc_route_table:
    region: "{{ ec2_region }}"
    vpc_id: "{{ vpc_info.vpc.id }}"
    subnets: "{{ subnets_ec2_ids }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw_info.gateway_id }}"
    resource_tags:
      "Name": "{{ environment_name }}_outbound"
      "Environment": "{{ environment_name }}"

