---
# tasks file for subnet
- name: ensure that subnets are present
  ec2_vpc_subnet:
    region: "{{ ec2_region }}"
    state: present
    vpc_id: "{{ vpc_info.vpc.id }}"
    cidr: "{{ item.subnet }}"
    az: "{{ ec2_region }}{{ item.az }}"
    resource_tags: 
      "Name": "{{ environment_name }}_{{ item.use }}_{{ ec2_region }}{{ item.az }}"
      "Environment": "{{ environment_name }}"
      "Use": "{{ item.use }}"
  with_items: "{{ the_subnets }}"
  

- name: gather information about the ec2 subnets 
  ec2_vpc_subnet_facts:
    region: "{{ ec2_region }}"
    filters:
      "tag:Use": "ec2"
      "tag:Environment": "{{ environment_name }}"
  register: subnets_ec2

- name: register just the ID for each subnets
  set_fact:
    subnets_ec2_ids: "{{ subnets_ec2.subnets| map(attribute='id') | list }}"

- name: print all the ids we have registered
  debug:
    msg: "{{subnets_ec2_ids}}" 

